In [ ]:
pip install numpy

In [ ]:
import numpy as np


In [ ]:
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_3d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3d)
print(arr_2d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
2


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])
print(arr_3d)
print(arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
3


In [ ]:
#zeros
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#random
random_arr=np.random.random((2,2))
print(random_arr)

[[0.08364122 0.08486171]
 [0.27464813 0.20349035]]


In [ ]:
#identity
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#array with range of values
range_arr=np.arange(0,10,2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
#Array attributes
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)
print("Dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data type: int64
Dimensions: 2


In [ ]:
# You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

# Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
# You received the following data:
# Your tasks are:
# Create NumPy arrays
# Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
# Print the array.
# Check array properties
# Print the shape, size, data type, and number of dimensions of temp_data.
# Add a third greenhouse
# The third greenhouse (GH3) records [21, 23, 22].
# Create a new array updated_temp_data that includes all three greenhouses.
# Generate supporting data
# Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
# Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
# Display all arrays
# Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

temp_data=np.array([[22,25,20],[24,26,23]])
print("temp_data:\n",temp_data)
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data type:",temp_data.dtype)
print("Numbeer of dimensions:",temp_data.ndim)
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print("updated_temp_data:\n",updated_temp_data)
print("greenhouse_identity:\n",greenhouse_identity)
print("sensor_error_flags:\n",sensor_error_flags)


temp_data:
 [[22 25 20]
 [24 26 23]]
Shape: (2, 3)
Size: 6
Data type: int64
Numbeer of dimensions: 2
updated_temp_data:
 [[22 25 20]
 [24 26 23]
 [21 23 22]]
greenhouse_identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
sensor_error_flags:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Indexing and slicingg
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,2])
print(arr[1,-1])
print(arr[1,-2])
print(arr)
print(arr[0:2,0:2])
print(arr[:,1 :])

30
60
50
[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]]
[[20 30]
 [50 60]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print("number of Apples shipped on Wednesday:",shipments[0,2])
print("number of Oranges shipped on Sunday:",shipments[1,6])
print("weekday shipments (Mon–Fri) for all fruits:",shipments[:,0:5])
print("weekend shipments (Sat & Sun):",shipments[:,5:7])
print("Apples from Wednesday to Saturday.:",shipments[0:1,2:6])
print("Original Saturday shipment of Apples:",shipments[0,5])
shipments[0,5]=100
print("Updated Saturday shipment of Apples:",shipments[0,5])

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
number of Apples shipped on Wednesday: 55
number of Oranges shipped on Sunday: 75
weekday shipments (Mon–Fri) for all fruits: [[50 60 55 70 65]
 [40 45 50 60 55]]
weekend shipments (Sat & Sun): [[80 90]
 [70 75]]
Apples from Wednesday to Saturday.: [[55 70 65 80]]
Original Saturday shipment of Apples: 80
Updated Saturday shipment of Apples: 100


In [ ]:
#Array operations
#Arithmetic
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a*2)
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[5 7 9]
[ 4 10 18]
[2 4 6]
[[19 22]
 [43 50]]


In [ ]:
#Broadcasting
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a+b)
print(np.divide(b,a))
print(np.mod(b,a))
print(np.power(b,a))

[[11 22 33]
 [14 25 36]]
[[10.  10.  10. ]
 [ 2.5  4.   5. ]]
[[0 0 0]
 [2 0 0]]
[[       10       400     27000]
 [    10000   3200000 729000000]]


In [ ]:
#Universal functions
arr=np.array([4,9,16])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
#2. Exponential and Logarithmic ufuncs
print(np.exp(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.expm1(arr) )
#3. Trigonometric ufuncs
x=np.array([0,30,45,60,90])
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)

[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[2. 3. 4.]
[1.38629436 2.19722458 2.77258872]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[1.38629436 2.19722458 2.77258872]
[0.60205999 0.95424251 1.20411998]
[2.       3.169925 4.      ]
[5.35981500e+01 8.10208393e+03 8.88610952e+06]


/tmp/ipython-input-1306425130.py:17: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)
/tmp/ipython-input-1306425130.py:18: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
#4. Rounding ufuncs
x=np.array([1.23456,2.34567,3.45678])
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)

array([1., 2., 3.])

In [ ]:
#5. Statistical ufuncs (Operate along an axis or entire array)
x=np.array([[1,2,3],[4,5,6]])
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)

np.int64(720)

In [ ]:
# 6. Logical ufuncs
x=np.array([True,False,True])
y=np.array([True,True,False])
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)

array([False,  True,  True])

In [ ]:
#7. Comparison ufuncs(Return Boolean arrays)
x=np.array([1,2,3])
y=np.array([3,2,1])
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)

In [ ]:
# 8. Bitwise ufuncs (Operate on integers)
x=np.array([1,2,3])
y=np.array([4,5,6])
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

array([-2, -3, -4])

You are a data engineer at a renewable-energy company that runs 3 solar farms.
Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)
Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.

In [111]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.stack((farmA,farmB,farmC),axis=0)
print(production_all)
print(production_all.shape)
print(production_all.size)
print(production_all.dtype)
print(production_all.ndim)
total_per_farm=np.sum(production_all,axis=(1,2))
print(total_per_farm)
print(np.mean(production_all,axis=(1,2)))
print(np.std(production_all,axis=(1,2)))
print(np.var(production_all,axis=(1,2)))
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print(weighted_per_panel)
production_all[:,1,:]=production_all[:,1,:]+0.5
print(production_all)
print(np.add(production_all,production_all))
print(np.subtract(production_all,production_all))
print(np.multiply(production_all,production_all))
print(np.divide(production_all,production_all))
print(np.power(production_all,production_all))
print(np.mod(production_all,production_all))
print(np.exp(production_all))
print(np.expm1(production_all))
print(np.log(production_all))
print(np.log10(production_all))
print(np.log2(production_all))
print(np.sin(production_all))
print(np.cos(production_all))
print(np.tan(production_all))
print(np.arcsin(production_all))
print(np.arccos(production_all))
print(np.arctan(production_all))
print(np.degrees(production_all))
print(np.radians(production_all))
print(np.round(production_all))
print(np.floor(production_all))
print(np.ceil(production_all))
print(np.trunc(production_all))
print(np.greater(production_all,production_all))
print(np.less(production_all,production_all))
print(np.equal(production_all,production_all))
print(np.not_equal(production_all,production_all))
print(np.greater_equal(production_all,production_all))
print(np.less_equal(production_all,production_all))
print(np.logical_and(production_all,production_all))
print(np.logical_or(production_all,production_all))
print(np.logical_not(production_all))
print(np.logical_xor(production_all,production_all))
print(np.min(production_all,axis=(1,2)))
print(np.max(production_all,axis=(1,2)))
print(np.any(production_all,axis=(1,2)))
print(np.all(production_all,axis=(1,2)))
panel(np.all(production_all))
panel_totals_per_farm=np.sum(production_all,axis=2)
print(panel_totals_per_farm)
needs_maintenance=np.any(panel_totals_per_farm<40,axis=1)
print(needs_maintenance)
overall_total=np.sum(production_all)
print(overall_total)
peak_hour_value=np.max(production_all)
print(peak_hour_value)
peak_hour_index=np.argmax(production_all)
print(peak_hour_index)
average_per_panel=np.mean(production_all,axis=0)
print(average_per_panel)


[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
(3, 4, 3)
36
int64
3
[126 234 174]
[10.5 19.5 14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
[[[20 24 22]
  [18 22 20]
  [24 26 28]
  [16 14 18]]

 [[40 38 42]
  [36 40 38]
  [44 46 42]
  [34 36 32]]

 [[30 32 28]
  [28 26 30]
  [32 34 36]
  [24 22 26]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[100 144 121]
  [ 81 121 100]
  [144 169 196]
  [ 64  49  81]]

 [[400 361 441]
  [324 400 361]
  [484 529 441]
  [289 324 256]]

 [[225 256 196]
  [196 169 225]
  [256 289 324]
  [1

/tmp/ipython-input-1136820436.py:34: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(production_all))
/tmp/ipython-input-1136820436.py:35: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(production_all))


In [113]:
arr=np.array([[1,2,3],[4,5,6]])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [115]:
#stack
#vertical stack
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(np.vstack((a,b,c)))
#horizontal stack
print(np.hstack((a,b,c)))
#split
arr=np.array([1,2,3,4,5,6])
print(np.split(arr,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [117]:
arr=np.array([1,2,3,4,5,6])
print(arr[arr>3])
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

[4 5 6]
[10 30]


In [122]:
#copy vs view
arr=np.array([1,2,3,4,5,6])
view=arr.view()
view[0]=12
print(arr)
copy=arr.copy()
copy[0]=10
b=np.array([1,2,3])

[12  2  3  4  5  6]


In [125]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [151]:
arr_1d=np.arange(10,51)
print(arr_1d)
r=np.random.rand(3,3)
print(r)
print(r.shape)
print(r.size)
print(r.dtype)
print(r.ndim)
print(arr_1d+5)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.multiply(a,b))
arr=np.arange(1,26).reshape(5,5)
print(arr)
print("first row:",arr[0,:])
print("last column:",arr[:,4])
print("subarray of the first three rows and first two columns",arr[:3,:2])
random_arr=np.random.randint(10,100,10)
print(random_arr)
print("max value:",np.max(random_arr))
print("min value:",np.min(random_arr))
print("mean:",np.mean(random_arr))
print("std:",np.std(random_arr))
arr=np.arange(1,13).reshape(3,4)
print(arr)
callable=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([10,20,30])
print(np.add(c,d))
ele=np.random.randint(1,50,15)
print(ele)
print(ele[ele%5==0])
print(np.dot(a,b))
#advanced indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
print(arr[[0,1,2,3],[0,1,2,3]])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.27419492 0.89542528 0.02369582]
 [0.63924437 0.19567672 0.44753095]
 [0.36558218 0.12375101 0.12483815]]
(3, 3)
9
float64
2
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row: [1 2 3 4 5]
last column: [ 5 10 15 20 25]
subarray of the first three rows and first two columns [[ 1  2]
 [ 6  7]
 [11 12]]
[86 62 80 69 38 72 27 38 27 58]
max value: 86
min value: 27
mean: 55.7
std: 20.66422028531442
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[17 28 39]
[45 17 38 31  1 10 29 47 20 39 28 40 36 41 46]
[45 10 20 40]
[[19 22]
 [43 50]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
